noAccessTokenRequiredEndpoints: /auth

defaultRedirectUrl: http://localhost:3000/github-redirect

github:
  login-base: https://github.com/login/oauth/
  login-redirect: authorize?client_id=${GITHUB_CLIENT_ID}&redirect_uri=${defaultRedirectUrl}&state={state}&scope={scope}
  login-get-access-token: access_token?client_id=${GITHUB_CLIENT_ID}&client_secret=${GITHUB_CLIENT_SECRET}&code={code}&redirect_uri=${defaultRedirectUrl}&state={state}
  api-base: https://api.github.com/
  api-user: user
  api-emails: user/emails

spring:
  profiles:
    active: development
  datasource:
    url: "jdbc:postgresql:hostiflix"
    username: "postgres"
    password: "password"
    driver-class-name: org.postgresql.Driver

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL9Dialect

jedisConFactory:
  hostname: localhost
  port: 6379

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver