spring:
  datasource:
    url: jdbc:postgresql:hostiflix
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  second-datasource:
    url:
    username:
    password:
    driver-class-name:

  jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true

  application:
    name: demoservice

noAccessTokenRequiredEndpoints: /auth

jedisConFactory:
  hostname: localhost
  port: 6379

defaultRedirectUrl: http://localhost:3000/github-redirect

github:
  login-base: https://github.com/login/oauth/
  login-redirect: authorize?client_id=${GITHUB_CLIENT_ID}&redirect_uri=${defaultRedirectUrl}&state={state}&scope={scope}
  login-get-access-token: access_token?client_id=${GITHUB_CLIENT_ID}&client_secret=${GITHUB_CLIENT_SECRET}&code={code}&redirect_uri=${defaultRedirectUrl}&state={state}
  api-base: https://api.github.com/
  api-user: user
  api-emails: user/emails